<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Annotations\CustomAnnotation'                         => __DIR__ . '/CustomAnnotation.php',
  'Annotations\Description'                  		 => __DIR__ . '/Description.php',
  
  'Annotations\Service'                  		 => __DIR__ . '/Service/Service.php',  
);