<?php 
  $active = 0;
  switch($this->slug) {
    case "catalogo":
      $active = 1;
      break;
    case "blog":
    case "nota":
      $active = 2;
      break;
    case "local":
      $active = 3;
      break;
  }
?>
<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>La Casa de Cosas</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="favicon.ico" />
<link rel="stylesheet" type="text/css" href="/css/styles.css">
<link rel="stylesheet" href="/css/flexslider.css" type="text/css" media="screen" />
<link rel="stylesheet" type="text/css" href="/css/elastislide.css" />
<link href='http://fonts.googleapis.com/css?family=Raleway:700,500,400' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/css/jquery.bxslider.css" type="text/css" media="screen" />
<meta property="og:image" content="" /><!-- facebook tag -->
<meta property="og:description" content=""/><!-- facebook tag -->
<meta name="Author" content="La Casa de Cosas" />
<meta name="description" content="" />
<meta name="keywords" content="">
<script type="text/javascript" src="/js/jquery-1.11.0.min.js"></script>
<!--[if lt IE 9]>
  <script src="/js/html5shiv.js"></script>
<![endif]-->
<script src="/js/smoothscroll.js" type="text/javascript"></script>
<script src="/js/responsive-accordion.min.js" type="text/javascript"></script>
<script src="/js/backbone.js" type="text/javascript"></script>
<script src="/js/catalogo.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jquery.idTabs.min.js"></script>
</head>
<body>
	<div class="content">
		<header>
			<a class="logo" href="/"><img src="/img/la_casa_logo.png" alt="La Casa de Cosas"></a>
			<span>
				<nav>
					<ul>
						<li><a <?php if($active == 0) echo 'class="bg-verde"'; ?> href="/">INICIO</a> |</li>
						<li><a <?php if($active == 1) echo 'class="bg-verde"'; ?> href="/catalogo">CATÁLOGO</a> |</li>
						<li><a <?php if($active == 2) echo 'class="bg-verde"'; ?> href="/blog">BLOG</a> |</li>
						<li><a <?php if($active == 3) echo 'class="bg-verde"'; ?> href="/local">LOCAL</a></li>
					</ul>
				</nav>
				<div class="busqueda" id="busqueda">
					<div class="busqueda02" id="busqueda02">
						<input id="newsSearchBoxKeyword" placeholder="Buscar...">
						<a href="#" id="btn-buscar" class="btn_buscar"><img src="/img/btn_buscar.png"></a>
					</div>
				</div>
				<div class="redes-sociales">
					<a href="#" target="_blank"><div class="face"></div></a>
					<a href="#" target="_blank"><div class="twitter"></div></a>
					<a href="#" target="_blank"><div class="pinterest"></div></a>
					<a href="#" target="_blank"><div class="tumblr"></div></a>
					<a href="#" target="_blank"><div class="instagram"></div></a>
				</div>
			</span>
		<div class="clear"></div>
		</header>
	<!-- end header -->
		    <?php echo $this->content; ?>
	<footer>
		<span>
			<p>© 2014 La Casa de Cosas.</p>
			<nav>
				<ul>
					<li><a href="/">INICIO</a> |</li>
					<li><a href="/catalogo">CATÁLOGO</a> |</li>
					<li><a href="/blog">BLOG</a> |</li>
					<li><a href="/local">LOCAL</a></li>
				</ul>
			</nav>
			<!-- <div class="buscador">
			</div> -->
			<div class="redes-sociales">
				<a href="#" target="_blank"><div class="face"></div></a>
				<a href="#" target="_blank"><div class="twitter"></div></a>
				<a href="#" target="_blank"><div class="pinterest"></div></a>
				<a href="#" target="_blank"><div class="tumblr"></div></a>
				<a href="#" target="_blank"><div class="instagram"></div></a>
			</div>
		</span>
	</footer>
<script defer src="/js/jquery.flexslider.js"></script>
<script type="text/javascript">
$(window).load(function() {
  $('.flexslider').flexslider({
    animation: "slide",
    prevText: "",           //String: Set the text for the "previous" directionNav item
    nextText: "",               //String: Set the text for the "next" directionNav item
  });
  if($(location.hash).length) {
      var secc = location.hash;
      secc = secc.replace("#","");
      $(".idTabs > li > a").each(function(item) {
		console.log($(this));
             $(this).removeClass("selected");
             var id = $(this).attr("id");
             id = id.replace("li-","");
             $("#"+id).hide();
      });
      $("#li-"+secc).addClass("selected"); 
      $("#"+secc).show();
  }; 
});
  </script>
	</div><!-- end content -->
</body>
</html>