<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>BotYaoi</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="/css/styles.css">
<link rel="stylesheet" href="/css/flexslider.css" type="text/css" media="screen" />
<link rel="stylesheet" type="text/css" href="/css/elastislide.css" />
<link href='http://fonts.googleapis.com/css?family=Raleway:700,500,400' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/css/jquery.bxslider.css" type="text/css" media="screen" />
<link rel="stylesheet" type="text/css" href="/css/prettyPhoto.css" />
<script type="text/javascript" src="/js/jquery-1.11.0.min.js"></script>
<!--[if lt IE 9]>
  <script src="/js/html5shiv.js"></script>
<![endif]-->
<script src="/js/smoothscroll.js" type="text/javascript"></script>
<script src="/js/responsive-accordion.min.js" type="text/javascript"></script>
<script src="/js/backbone.js" type="text/javascript"></script>
<script src="/js/catalogo.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jquery.idTabs.min.js"></script>
<script src="/js/jquery.smoothZoom.min.js"></script>
<script src="/js/jquery.easing.min.js" type="text/javascript"></script>
<script src="/js/jquery.prettyPhoto.js" type="text/javascript"></script>
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.css" />
<script src="http://code.jquery.com/mobile/1.0.1/jquery.mobile-1.0.1.min.js"></script>
	
</head>
<body>
	<div class="content" data-role="page">
		<div data-role="header">
			<span>
			</span>
		<div class="clear"></div>
		</div>
	<!-- end header --><div id="c" data-role="content">
		    <?php echo $this->content; ?>
			</div>
	<footer>
		<span>
			<!-- <div class="buscador">
			</div> -->
		</span>
	</footer>
<script defer src="/js/jquery.flexslider.js"></script>
<script type="text/javascript">
$(window).load(function() {
  $('.flexslider').flexslider({
    animation: "slide",
    prevText: "",           //String: Set the text for the "previous" directionNav item
    nextText: "",               //String: Set the text for the "next" directionNav item
  });

  $("#btn-buscar").click(function(e){
	e.preventDefualt;
	var value = $("#newsSearchBoxKeyword").val();
	if(value.length) {
		$("#busq").submit();
	}
  });
  
  if(location.hash.length) {
      var secc = location.hash;
      secc = secc.replace("#","");

      $("#producto-"+secc).click();

      $(".idTabs > li > a").each(function(item) {
		console.log($(this));
             $(this).removeClass("selected");
             var id = $(this).attr("id");
             id = id.replace("li-","");
             $("#"+id).hide();
      });
      $("#li-"+secc).addClass("selected"); 
      $("#"+secc).show();
  }; 
});
  </script>
	</div><!-- end content -->
</body>
</html>