<div class="w-section"></div>
<div id="m-status" style="margin-bottom: 300px">

	<h2 class="title">Listado</h2>
	<div class="block">
	
	<table id="tablelist" class="full tablesorter">
	<thead>
	  <tr>
	    <?php foreach($this->cols as $cols) : ?>
	      <th class="header"><?php echo $cols['desc'] ;?></th>
	    <?php endforeach ?>
	      <?php if(($this->perm['baja']==true)||($this->perm['modificacion']==true)) : ?><th class="header">Editar / Borrar</th><?php endif ?>
	  </tr>
	</thead>
	<tbody>
	  <tr>
	    <?php foreach($this->list as $list) : ?>
	      <tr>
	      <?php foreach($this->cols as $key => $value) : ?>
		<td><?php echo $this->annotation_list($value['column'],$list->get($key)) ?></td>
	      <?php endforeach ?>
	      <?php if(($this->perm['baja']==true)||($this->perm['modificacion']==true)) : ?>
		<td><?php if($this->perm['modificacion']==true) : ?><a href="<?php echo $this->basePath(); ?>/admin/<?php echo $this->table ?>/update/<?php echo $list->get('id')?>" class="btn site btn-sm">Editar</a> &nbsp;<?php endif ?><?php if($this->perm['baja']==true) : ?>&nbsp; <a href="<?php echo $this->basePath(); ?>/admin/<?php echo $this->table ?>/delete/<?php echo $list->get('id')?>" class="btn error site btn-sm">Borrar</a><?php endif ?></td>
	      <?php endif ?>
	      </tr>
	    <?php endforeach ?>
	  </tr>	
	</tbody>
	<tfoot>
	  <tr>
	    <td><a href="<?php echo $this->basePath();?>/admin/<?php echo $this->table ?>/list/<?php echo ($this->id-1);?>" class="btn info" <?php echo ($this->id==0?"disabled":"")?>>Anterior</a></td>
	    <td colspan="<?php echo count($this->cols)-1 ?>"><?php if($this->perm['alta']==true) : ?><a href="<?php echo $this->basePath();?>/admin/<?php echo $this->table ?>/create" class="btn success">Nuevo</a><?php endif ?></td>
	    <td><a href="<?php echo $this->basePath();?>/admin/<?php echo $this->table ?>/list/<?php echo ($this->id+1);?>" class="btn info" <?php echo ($this->id==$this->max-1?"disabled":"")?>>Siguiente</a></td>
	  </tr>
	</tfoot>	
	</table>
	</div>
</div> 


