		<section class="home">
			<div class="mapa">
				<h3>ELEGÍ UN AMBIENTE DE LA CASA</h3>
				<div class="row clear">
					<div class="regalos">
						<a href="/catalogo/<?php echo $this->categorias['Regalos']['datos']->getId(); ?>"><img src="/img/regalos02.jpg"></a>
					</div>
					<div class="dormitorio">
						<a href="/catalogo/<?php echo $this->categorias['Dormitorio']['datos']->getId(); ?>"><img src="/img/dormitorio02.jpg"></a>
					</div>
					<div class="bano">
						<a href="/catalogo/<?php echo $this->categorias['Baño']['datos']->getId(); ?>"><img src="/img/bano02.jpg"></a>
					</div>
					<div class="ninos">
						<a href="/catalogo/<?php echo $this->categorias['Niños']['datos']->getId(); ?>"><img src="/img/ninos02.jpg"></a>
					</div>
				</div>
				<div class="row clear">
					<div class="cocina">
						<a href="/catalogo/<?php echo $this->categorias['Cocina']['datos']->getId(); ?>"><img src="/img/cocina02.jpg"></a>
					</div>
					<div class="comedor">
						<a href="/catalogo/<?php echo $this->categorias['Comedor']['datos']->getId(); ?>"><img src="/img/comedor02.jpg"></a>
					</div>
					<div class="living">
						<a href="/catalogo/<?php echo $this->categorias['Living']['datos']->getId(); ?>"><img src="/img/living02.jpg"></a>
					</div>
					<div class="exterior">
						<a href="/catalogo/<?php echo $this->categorias['Exterior']['datos']->getId(); ?>"><img src="/img/exterior02.jpg"></a>
					</div>
				</div>
			</div>
			<div class="slider-home">
				<div class="flexslider carousel">
		          <ul class="slides">
					<?php foreach($this->slider as $slide) : ?>
					 <a href="<?php echo $slide->getLink(); ?>" target="_blank">
					    <li>
						  <div class="title <?php echo $slide->getColor()->getClass();?>"><?php echo $slide->getTitulo(); ?></div>
						  <img src="/<?php echo $slide->getFirstImg(); ?>">
					    </li>
					</a>
			  	    	<?php endforeach ?>
		          	</ul>
		        </div>
	        </div>
	        <div class="banner01">
			  <?php foreach($this->bann01 as $banner) : ?>
			     
				 <a href="<?php echo $banner->getLink(); ?>" target="_blank">
 				    <div class="title <?php echo $banner->getColor()->getClass();?>"><?php echo $banner->getTitulo(); ?></div>
				    <img src="/<?php echo $banner->getFirstImg(); ?>">
				    <p><?php echo $banner->getTexto(); ?></p>
				 </a>
			   
			  <?php endforeach ?>		
	       	</div> 
		</section>
		<aside class="aside-home">
			<div class="banner02">
			  <?php foreach($this->bann02 as $banner) : ?>
			     
				 <a href="<?php echo $banner->getLink(); ?>" target="_blank">
 				    <div class="title <?php echo $banner->getColor()->getClass();?>"><?php echo $banner->getTitulo(); ?></div>
				    <img src="/<?php echo $banner->getFirstImg(); ?>">
				    <p><?php echo $banner->getTexto(); ?></p>
				 </a>
			    
			  <?php endforeach ?>
	       	</div>
	       	<div class="banner03">
			  <?php foreach($this->bann03 as $banner) : ?>
			 
				 <a href="<?php echo $banner->getLink(); ?>" target="_blank">
 				    <div class="title <?php echo $banner->getColor()->getClass();?>"><?php echo $banner->getTitulo(); ?></div>
				    <img src="/<?php echo $banner->getFirstImg(); ?>">
				    <p><?php echo $banner->getTexto(); ?></p>
				 </a>
			  
			  <?php endforeach ?>
	       	</div>  
		</aside>
		<div class="clear"></div>
