		<section class="home">
			<div class="mapa">
				<h3>ELEGÍ UN AMBIENTE DE LA CASA</h3>
				<div class="row clear">
					<div class="regalos">
						<a href="#"><img src="/img/regalos02.jpg"></a>
					</div>
					<div class="dormitorio">
						<a href="#"><img src="/img/dormitorio02.jpg"></a>
					</div>
					<div class="bano">
						<a href="#"><img src="/img/bano02.jpg"></a>
					</div>
					<div class="ninos">
						<a href="#"><img src="/img/ninos02.jpg"></a>
					</div>
				</div>
				<div class="row clear">
					<div class="cocina">
						<a href="#"><img src="/img/cocina02.jpg"></a>
					</div>
					<div class="comedor">
						<a href="#"><img src="/img/comedor02.jpg"></a>
					</div>
					<div class="living">
						<a href="#"><img src="/img/living02.jpg"></a>
					</div>
					<div class="exterior">
						<a href="#"><img src="/img/exterior02.jpg"></a>
					</div>
				</div>
			</div>
			<div class="slider-home">
				<div class="flexslider carousel">
		          <ul class="slides">
			            <li>
			            	<div class="title naranja">DISEÑO</div>
			  	    	    <img src="/img/slide-home.jpg">
			  	    	</li>
			  	    	<li>
			  	    		<div class="title naranja">DISEÑO</div>
			  	    	    <img src="/img/slide-home.jpg">
			  	    	</li>
			  	    	<li>
			  	    		<div class="title naranja">DISEÑO</div>
			  	    	    <img src="/img/slide-home.jpg">
			  	    	</li>
		          	</ul>
		        </div>
	        </div>
	        <div class="banner01">
	        	<div class="title lila">CONCURSO</div>
	        	<img src="/img/ejemplo02.jpg">
	        	<p>Participá en facebook y ganate un juego de tazas</p>
	       	</div> 
		</section>
		<aside class="aside-home">
			<div class="banner02">
				<div class="title verde">NUEVO</div>
	        	<img src="/img/ejemplo03.jpg">
	        	<p>Participá en facebook y ganate un juego de tazas</p>
	       	</div>
	       	<div class="banner03">
	       		<div class="title naranja">DISEÑO</div>
	        	<img src="/img/ejemplo01.jpg">
	        	<p>Participá en facebook y ganate un juego de tazas</p>
	       	</div>  
		</aside>
		<div class="clear"></div>