		<section>
			<div class="contacto-mapa">
				<img id="yourImageID" src="/img/mapa-contacto.jpg" />
			</div>
			<div class="contacto-fotos">
				<ul>
					<li><img src="/img/contacto01.jpg"></li>
					<li><img src="/img/contacto02.jpg"></li>
					<li><img src="/img/contacto03.jpg"></li>
				</ul>
			</div>
		</section>
		<aside>
			<div class="contacto-info">
					<div class="title lila">CONTACTO</div>

					<?php echo $this->contacto->getValue() ?>

					<p><a href="mailto:<?php echo str_replace("</p>","",str_replace("<p>","",$this->email->getValue())) ?>"><?php echo $this->email->getValue() ?></a></p>

					<?php echo $this->horario->getValue() ?>
					
					<?php echo $this->transporte->getValue() ?>
			</div>
		</aside>
		<div class="clear"></div>
