		<section>
			<div class="contacto-mapa">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3285.8404765235596!2d-58.47194589999999!3d-34.55759419999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcb6842ce20f3d%3A0xc1871c843741c539!2sCapit%C3%A1n+General+Ram%C3%B3n+Freire+3100!5e0!3m2!1sen!2sar!4v1404876547203" width="600" height="450" frameborder="0" style="border:0"></iframe>
			</div>
			<div class="contacto-fotos">
				<ul>
					<li><img src="img/contacto01.jpg"></li>
					<li><img src="img/contacto02.jpg"></li>
					<li><img src="img/contacto03.jpg"></li>
				</ul>
			</div>
		</section>
		<aside>
			<div class="contacto-info">
					<div class="title lila">CONTACTO</div>

					<p>Tel: (011) 4543-7910
					Freire 3100, esquina Iberá. Coghlan,
					Ciudad Autónoma de Buenos Aires</p>

					<p><a href="mailto:lacasadecosas@yahoo.com.ar">lacasadecosas@yahoo.com.ar</a></p>

					<p>Abierto de lunes a sábados 
					de 9:00 a 20:00 hs.</p>

					<p><strong>Transportes que te acercan:</strong></p>

					<p>- Líneas de colectivos -<br>
					19, 29, 41, 67, 76, 107, 130,
					151, 169, 175.</p>

					</p>- Subte D - <br>
					Estación Congreso + 10 cuadras</p>

					<p>- Tren Mitre -<br> 
					Estación Coghlan + 10 cuadras</p>
			</div>
		</aside>
		<div class="clear"></div>
