<?php
    function limpiar($String)
    {
	$String = str_replace(array('á'),'a',$String);
	$String = str_replace(array('é'),'e',$String);
	$String = str_replace(array('í'),'i',$String);
	$String = str_replace(array('ó'),'o',$String);
	$String = str_replace(array('ú'),'u',$String);
	$String = str_replace(array('ñ'),'n',$String);
	$String = str_replace(array(' '),'-',$String);
	return $String;
     }
?>
<div id="overlay">
	<div class="cuadro">
		<article>
			<ul class="bxslider">
			  <?php foreach($this->prod->getImgs() as $img) : ?>
			      <li><img src="/<?php echo $img->getUri(); ?>" /></li>
			  <?php endforeach ?> 
			</ul>
			<div id="bx-pager">
			  <?php $i = 0; ?>
			  <?php foreach($this->prod->getImgs() as $img) : ?>
			      <a data-slide-index="<?php echo $i; ?>" href=""><img src="/<?php echo $img->getUri(); ?>" /></a>
			  <?php $i++; ?>
			  <?php endforeach ?> 
			</div>							
		</article>
		<article>
			<h5><?php echo $this->prod->getName(); ?></h5>
			<p><?php echo $this->prod->getAutor(); ?></p>
			<p class="precio">$<?php echo $this->prod->getPrecio(); ?></p>
			<hr />
			<p class="item">
				<?php echo substr(substr($this->prod->getDesc(),3),0,-4); ?>
			</p>
			<img src="/img/catalogo-<?php echo limpiar(strtolower($this->prod->getCategoria()->getPadre()->getName())); ?>.png">
		</article>
	<div class="close">X</div>
	</div>
</div>
<script>
    var boton04 = $('.close');
    boton04.click(
    function (){
        $('#overlay').hide(200);
    });  
    $('.bxslider').bxSlider({
	  pagerCustom: '#bx-pager'
    });
</script>